# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TableViewWithRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TableViewWithRxSwift
  pod 'RxSwift', '~> 6'
  pod 'RxCocoa', '~> 6'
  pod 'RxDataSources', '~> 5.0'
  
end
